### ISSUE TITLE
create_function() is deprecated

### ISSUE THREAD

**Issue by halojoy** [dotclear/dotclear#1]
I run PHP 7.2.3.
When I want to install I get this notice:
Deprecated: Function create_function() is deprecated in C:\Apache24\htdocs\dotclear2131\inc\libs\clearbricks\common\lib.l10n.php on line 640

**Comment by franck-paul** [comment]
Yes we know, the next Dotclear 2.14 will be compliant with 7.2. (see https://github.com/dotclear/clearbricks/commit/5a6945eb7e785d95b12bf5a477040a3df9a010b1#diff-0f2e1d6c92e50eaa75c25238ab0b9b46 and some others commits)
