### ISSUE TITLE
Adding attachment to post impossible

### ISSUE THREAD

**Issue by padawan83** [dotclear/dotclear#8]
2.16-dev-r202002281754

When adding an attachment to a post, a dialog box appears saying that changes on the page have been made and asks if you want to stay on the page or leave it.

If you accept the page change page, you are redirected to the media manager to choose your attachment but the click does not insert the attachment

But it is not only with attachments :  when you navigate from post to post using the prev and next buttons, the same dialog box appears to tell you you have unsaved modifications even though you have made none

**Comment by franck-paul** [comment]
May be a (javascript) cache problem? I can't reproduce this.

**Comment by franck-paul** [comment]
By the way, the issue tracker on our official repo is now open for github accounts.
See https://git.dotclear.org/dev/dotclear

**Comment by padawan83** [comment]
Sorry for the noise : it seems to be only with Firefox (73.0.1 Linux Mint), and not all the time... it works fine with Chromium browser. 

For the repo https://git.dotclear.org/dev/dotclear it refuses my github account and I can't login...

Philippe ;)

**Comment by franck-paul** [comment]
Tu as des détails sur le blème de connexion sur git.dotclear.org ?

**Comment by padawan83** [comment]
Oui : il fallait que je lise un peu mieux... Vraiment désolé.

Et le bug de confirmclose() tu l'as testé avec un Firefox ? Moi j'ai réparé le mien, créé un nouveau profil, mais ça continue à s'afficher aléatoirement.

**Comment by franck-paul** [comment]
> Oui : il fallait que je lise un peu mieux... Vraiment désolé.
> 
> Et le bug de confirmclose() tu l'as testé avec un Firefox ? Moi j'ai réparé le mien, créé un nouveau profil, mais ça continue à s'afficher aléatoirement.

Je vais tester avec FF pour voir…

**Comment by franck-paul** [comment]
Pas de souci avec FF non plus

**Comment by franck-tomek** [comment]
Pas de souci sous FF 73.0.1 non plus de mon côté.

**Comment by franck-paul** [comment]
Une piste ici : https://developer.mozilla.org/fr/docs/Web/Events/beforeunload

**Comment by franck-paul** [comment]
PS : Je vais transférer ce ticket chez nous dans la journée…

**Comment by franck-paul** [comment]
Bon j'ai beau avoir repris complètement la fonction confirmClose() qui marche à merveille, pas moyen de faire comprendre à ce couillon de Chrome (et consort) que le formulaire est clean et qu'i n'y a pas besoin d'une alerte.

J'y ai passé une bonne partie de la journée sans trouver comment faire !

**Comment by franck-paul** [comment]
Close here and opened [there](https://git.dotclear.org/dev/dotclear/issues/19)
